name: Downstream Updates
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [
          espressif-esp,
          gigadevice-gd32,
          microchip-atmega,
          nordic-nrf5x,
          nxp-lpc,
          raspberrypi-rp2040,
          stmicro-stm32,
        ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ZigEmbeddedGroup/${{ matrix.repo }}
        submodules: recursive
        fetch-depth: 0

    - name: Update
      id: update
      run: |
        cd deps/microzig
        git pull origin main
        echo "DESCRIPTION=$(git log -1 --pretty=%B | head -n 1)" >> $GITHUB_OUTPUT

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4.2.3
      with:
        token: ${{ secrets.PR_TOKEN }}
        branch: downstream/update-microzig
        commit-message: update microzig
        delete-branch: true
        title: Update microzig
        body: ${{ steps.update.outputs.DESCRIPTION }}
